version: '3.8'

services:

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
    volumes:
      - /home/jean/Documents/rabbitmq-data:/var/lib/rabbitmq
    networks:
      - tenet-network

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tenet_main
    ports:
      - "5433:5432"
    volumes:
      - /home/jean/Documents/postgres-data:/var/lib/postgresql/data
    networks:
      - tenet-network

  profile:
    image: tenet-profile:1.0.30
    container_name: tenet-profile
    restart: always
    depends_on:
      - postgres
    env_file:
      - /home/jean/dev/tenet-profile/cmd/.env
    ports:
      - "8082:8082"
    volumes:
      - /home/jean/Documents/tenet/profile-uploads:/app/uploads
    networks:
      - tenet-network

  tenet-main:
    image: tenet-main:1.0.26
    container_name: tenet-main26
    restart: always
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    networks:
      - tenet-network
  
  nginx:
    image: nginx:latest
    container_name: tenet-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/web:/usr/share/nginx/html:ro
    depends_on:
      - tenet-main
      - profile
    networks:
      - tenet-network

networks:
  tenet-network:
    driver: bridge